# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ebd4b5fbbf67a3152d41ad1cf009307652f7a0d572df2b7d0331fa2b4a5cd606cafb4e739794cb7130212c7b09f9cef41fe1ebd7e2fd8bed4e894031a3eebaf

test:
  secret_key_base: bb76458112adaf9217fcfaaa669e9a9ec98d7e16cdb7fe0b5bd7877ffd8c2aa87cdb751fb13441af29d128c990570e94c511eb7529d47006da3f65d672c3d6c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
